[workspace]
resolver = "3"
members = ["crates/*", "main"]

[workspace.dependencies]
imgui = "0.12.0"
vulkano = "0.35.2"
vulkano-shaders = "0.35.0"
glam = { version = "0.30.9", features = ["fast-math"] }
