[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
imgui = { workspace = true }
imgui-winit-support = "0.13.0"
vulkano = { workspace = true }
vulkano-shaders = { workspace = true }
vulkano-taskgraph = "0.35.1"
winit = "0.30.12"
